common_cfg:
  embed_dim: 64 
  activation:  relu  

encoder_cfg:
  gnn_cfg:
    gnn_cfg:
      node_dim: 3  
      edge_dim: 4  
      embedding_layer: 2 
      nhead: 4  
      layer_num: 4
      dropout: 0.1
      whole_batch_edge_processing: False  
      edge_norm: True 
    gff_cfg:
      layer: 2
  veh_dim: 5  
  embedding_layer: 2 
  enc_type: enc   
  layer_num: 2  
  nhead: 4  
  cross_attn_en: True

sel_encoder_cfg:
  input_dim: 66  
  nhead: 4  
  veh_dim: 64 
  seq_enc: pure_gru  #attn, gru, pure_gru, slice_gru, pure_attn
  veh_adding_method: cat
  seq_type: embed
  embed_slice: True
  slice_type: attn
  remain_veh_attn: False

actor_cfg:
  query_dim: 256  
  nhead: 4 
  ptr_fn: attn 
  pnorm: False

critic_cfg:
   query_dim: 256  
   nhead: 4 

# critic_cfg:
#    layer_num: 2

single_step: False

critic_detach: False

critic_list:
  - s
  - t
  - c